export const adminBreadcrumbs: Record<string, string[]> = {
  "/admin/overview": ["Dashboard", "Overview"],
  "/admin/style-catalog": ["Dashboard", "Style Catalog"],
  "/admin/style-catalog/add": ["Dashboard", "Style Catalog", "Add Style"],
  "/admin/style-catalog/edit": ["Dashboard", "Style Catalog", "Edit Style"],
  "/admin/categories": ["Dashboard", "Style Catalog", "Categories"],
  "/admin/categories/add": ["Dashboard", "Style Catalog", "Categories", "Add Category"],
  "/admin/categories/edit": ["Dashboard", "Style Catalog", "Categories", "Edit Category"],
  "/admin/home-feed": ["Dashboard", "Home Feed"],
  "/admin/home-feed/add": ["Dashboard", "Home Feed", "Add Section"],
  "/admin/home-feed/edit": ["Dashboard", "Home Feed", "Edit Section"],
  "/admin/wardrobe-categories": ["Dashboard", "Wardrobe Categories"],
  "/admin/wardrobe-categories/add": ["Dashboard", "Wardrobe Categories", "Add category"],
  "/admin/wardrobe-categories/edit": ["Dashboard", "Wardrobe Categories", "Edit category"],
  "/admin/try-on-jobs": ["Dashboard", "Try-On Jobs"],
  "/admin/try-on-jobs/details": ["Dashboard", "Try-On Jobs", "Job details"],
  "/admin/users": ["Dashboard", "Users"],
  "/admin/users/detail": ["Dashboard", "Users", "User details"],
  "/admin/app-content": ["Dashboard", "App Content"],
  "/admin/account": ["Dashboard", "Admin Account"],
  "/admin/token-management": ["Dashboard", "Token management"],
  "/admin/looks-history": ["Dashboard", "Looks / History"],
  "/admin/looks-history/details": ["Dashboard", "Looks / History", "Look details"],
  "/admin/notifications": ["Dashboard", "Notifications"],
  "/admin/notifications/campaigns/details": ["Dashboard", "Notifications", "Campaign details"],
  "/admin/devices": ["Dashboard", "Device Registry"],
  "/admin/system": ["Dashboard", "System Status"],
  "/admin/activity": ["Dashboard", "Activity log"],
};
